databases:
  - name: micronaut
    ipAllowList: []
    databaseName: micronaut_5bw7
    user: micronaut_5bw7_user

services:
  - type: web
    name: budget
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: micronaut
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false